baseURL = "https://domenico.click"
languageCode = 'en-us'
title = "DT"

theme = "ezhil"
copyright = "© Copyright - Creato da Domenico Toscano"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
subtitle = "Le pagine di Domenico Toscano e del social del futuro."
mode = "auto"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Tutto"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 10
